language: php
php:
    - "5.5"

before_script: 
	- composer install
	- wget https://scrutinizer-ci.com/ocular.phar

script: phpunit --bootstrap test/config.php --coverage-clover build/logs/clover.xml test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml